#!/bin/sh

str="global var"

foo() {
	local str="local var"
	echo "in foo"
	echo $str
}

echo "script starting"
echo $str

foo

echo "script ended"
echo $str

echo -e "JOJO \c"

read tmp
var=${tmp%%,*}
echo $tmp
echo $var

exit 0
