#!/bin/sh

echo "Is it afternoon? Please answer yes or no"
read timeofday

if [ $timeofday = "yes" ]; then
	echo "Good Afternoon"
elif [ $timeofday = "no" ]; then
	echo "Good morning"
else
	echo "wryyyyyyyyyyyy"
	exit 1
fi

exit 0
